services:
  booking-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=file:./dev.db
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
